version: '3.8'

services:

  mongo:
    container_name: mongo
    image: mongo:5.0
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"

  api:
    container_name: api-container
    restart: always
    volumes:
      - ./dist:/usr/src/ca-api/dist
    build: .
    ports:
      - 80:3000
    command: npm start
    links: 
    - mongo
    depends_on:
      - mongo
